server:
  port: 8080
  servlet:
    context-path: /library

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/manage_library"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true